/**
 * StreamSmart: Complete Colleges Database
 * Real Data: Fees, Rankings, Entrance Exams, and Placements
 */

// ════════════════════════════════════════════════
// RAW B.TECH COLLEGE DATA (130+ RECORDS)
// ════════════════════════════════════════════════
const BTECH_COLLEGES = {
    iits: [
        { id: 1, name: "IIT Madras", location: "Chennai, Tamil Nadu", state: "Tamil Nadu", type: "IIT", nirf: 1, naac: "A++", established: 1959, annualFees: "₹2,00,000", totalFees4yr: "₹8,00,000", entrance: "JEE Advanced", topBranches: ["CSE", "Electrical", "Aerospace"], avgPackage: "₹20–28 LPA", topRecruiters: "McKinsey, Apple, Google", website: "iitm.ac.in", highlight: "🥇 #1 NIRF Engineering Rank - Best in India" },
        { id: 2, name: "IIT Delhi", location: "New Delhi", state: "Delhi", type: "IIT", nirf: 2, naac: "A++", established: 1961, annualFees: "₹2,20,000", totalFees4yr: "₹8,80,000", entrance: "JEE Advanced", topBranches: ["CSE", "Electrical", "Production"], avgPackage: "22–30 LPA", topRecruiters: "Goldman Sachs, Microsoft, Google", website: "iitd.ac.in", highlight: "🏆 Best IIT for CSE placements in Delhi" },
        { id: 3, name: "IIT Bombay", location: "Mumbai, Maharashtra", state: "Maharashtra", type: "IIT", nirf: 3, naac: "A++", established: 1958, annualFees: "₹2,20,000", totalFees4yr: "₹8,80,000", entrance: "JEE Advanced", topBranches: ["CSE", "Electrical", "Mechanical"], avgPackage: "25–35 LPA", topRecruiters: "Google, Microsoft, Amazon", website: "iitb.ac.in", highlight: "🌆 Best for Finance + Tech. Mumbai advantage" },
        { id: 4, name: "IIT Kanpur", location: "Kanpur, Uttar Pradesh", state: "Uttar Pradesh", type: "IIT", nirf: 4, naac: "A++", established: 1959, annualFees: "₹2,12,000", totalFees4yr: "₹8,48,000", entrance: "JEE Advanced", topBranches: ["CSE", "Electrical", "Aerospace"], avgPackage: "20–28 LPA", topRecruiters: "Uber, Amazon, Microsoft", website: "iitk.ac.in", highlight: "💡 Best for research + innovation" },
        { id: 5, name: "IIT Kharagpur", location: "Kharagpur, West Bengal", state: "West Bengal", type: "IIT", nirf: 5, naac: "A++", established: 1951, annualFees: "₹1,48,700", totalFees4yr: "₹6,00,000", entrance: "JEE Advanced", topBranches: ["CSE", "Mechanical", "Mining"], avgPackage: "18–25 LPA", topRecruiters: "TCS, Qualcomm, Intel", website: "iitkgp.ac.in", highlight: "🏛️ Oldest IIT. Largest campus in India" },
        { id: 6, name: "IIT Roorkee", location: "Roorkee, Uttarakhand", state: "Uttarakhand", type: "IIT", nirf: 7, naac: "A++", established: 1847, annualFees: "₹2,17,000", totalFees4yr: "₹8,68,000", entrance: "JEE Advanced", topBranches: ["CSE", "ECE", "Mechanical"], avgPackage: "15–22 LPA", topRecruiters: "Amazon, Microsoft, TCS", website: "iitr.ac.in", highlight: "🏛️ Asia's oldest technical institute" },
        { id: 7, name: "IIT Guwahati", location: "Guwahati, Assam", state: "Assam", type: "IIT", nirf: 7, naac: "A++", established: 1994, annualFees: "₹2,24,500", totalFees4yr: "₹8,98,000", entrance: "JEE Advanced", topBranches: ["CSE", "ECE", "Design"], avgPackage: "14–20 LPA", topRecruiters: "Amazon, Flipkart, TCS", website: "iitg.ac.in", highlight: "🌿 Beautiful campus. Best in Northeast" },
        { id: 8, name: "IIT Hyderabad", location: "Hyderabad, Telangana", state: "Telangana", type: "IIT", nirf: 8, naac: "A+", established: 2008, annualFees: "₹2,37,500", totalFees4yr: "₹9,50,000", entrance: "JEE Advanced", topBranches: ["CSE", "AI", "ECE"], avgPackage: "12–18 LPA", topRecruiters: "Intel, Qualcomm, Amazon", website: "iith.ac.in", highlight: "🤖 1st IIT for AI. Strong startup culture" },
        { id: 9, name: "IIT Indore", location: "Indore, Madhya Pradesh", state: "Madhya Pradesh", type: "IIT", nirf: 17, naac: "A", established: 2009, annualFees: "₹2,20,000", totalFees4yr: "₹8,80,000", entrance: "JEE Advanced", topBranches: ["CSE", "ECE", "Mechanical"], avgPackage: "10–16 LPA", topRecruiters: "Amazon, Infosys, TCS", website: "iiti.ac.in", highlight: "🌟 Best engineering option in MP. IIT tag" },
        { id: 10, name: "IIT Bhubaneswar", location: "Bhubaneswar, Odisha", state: "Odisha", type: "IIT", nirf: 23, naac: "A", established: 2008, annualFees: "₹2,17,000", totalFees4yr: "₹8,68,000", entrance: "JEE Advanced", topBranches: ["CSE", "ECE", "Mechanical"], avgPackage: "9–14 LPA", topRecruiters: "TCS, Wipro, Infosys", website: "iitbbs.ac.in", highlight: "🌊 Growing IIT with research focus" },
        { id: 11, name: "IIT Mandi", location: "Mandi, Himachal Pradesh", state: "Himachal Pradesh", type: "IIT", nirf: 39, established: 2009, annualFees: "₹2,20,000", totalFees4yr: "₹8,80,000", entrance: "JEE Advanced", topBranches: ["CSE", "ECE", "Data Science"], avgPackage: "8–13 LPA", website: "iitmandi.ac.in", highlight: "🏔️ Scenic Himalayan campus" },
        { id: 12, name: "IIT Patna", location: "Patna, Bihar", state: "Bihar", type: "IIT", nirf: 38, established: 2008, annualFees: "₹2,10,000", totalFees4yr: "₹8,40,000", entrance: "JEE Advanced", topBranches: ["CSE", "ECE", "Mathematics"], avgPackage: "8–12 LPA", website: "iitp.ac.in", highlight: "📚 Good for Bihar students — IIT tag" },
        { id: 13, name: "IIT Jodhpur", location: "Jodhpur, Rajasthan", state: "Rajasthan", type: "IIT", nirf: 41, established: 2008, annualFees: "₹2,20,000", totalFees4yr: "₹8,80,000", entrance: "JEE Advanced", topBranches: ["CSE", "ECE", "Bioscience"], avgPackage: "8–13 LPA", website: "iitj.ac.in", highlight: "🏜️ Great campus in Rajasthan" }
    ],
    nits: [
        { id: 14, name: "NIT Trichy", location: "Tiruchirappalli", state: "Tamil Nadu", type: "NIT", nirf: 9, naac: "A++", established: 1964, annualFees: "₹1,25,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "Mechanical"], avgPackage: "₹10–18 LPA", topRecruiters: "Zoho, Amazon, TCS", website: "nitt.edu", highlight: "⭐ #1 NIT in India. Excellent placements" },
        { id: 15, name: "NIT Warangal", location: "Warangal", state: "Telangana", type: "NIT", nirf: 26, naac: "A++", established: 1959, annualFees: "₹1,10,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "Mechanical"], avgPackage: "8–15 LPA", topRecruiters: "Microsoft, Amazon, Wipro", website: "nitw.ac.in", highlight: "🌟 Top NIT for tech companies" },
        { id: 16, name: "NIT Surathkal", location: "Mangalore", state: "Karnataka", type: "NIT", nirf: 23, naac: "A+", established: 1960, annualFees: "₹1,20,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "IT"], avgPackage: "9–14 LPA", website: "nitk.ac.in", highlight: "🌊 Sea-side campus advantage" },
        { id: 17, name: "NIT Calicut", location: "Kozhikode", state: "Kerala", type: "NIT", nirf: 28, naac: "A+", established: 1961, annualFees: "₹1,10,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "Civil"], avgPackage: "8–14 LPA", website: "nitc.ac.in", highlight: "🌴 Top NIT in South India" },
        { id: 18, name: "NIT Rourkela", location: "Rourkela", state: "Odisha", type: "NIT", nirf: 22, naac: "A++", established: 1961, annualFees: "₹1,10,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "Mining"], avgPackage: "7–13 LPA", website: "nitrkl.ac.in", highlight: "⚙️ Excellent for core & metallury" },
        { id: 19, name: "VNIT Nagpur", location: "Nagpur", state: "Maharashtra", type: "NIT", nirf: 40, naac: "A+", established: 1960, annualFees: "₹1,10,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "Mechanical"], avgPackage: "7–12 LPA", website: "vnit.ac.in", highlight: "🏙️ Best NIT in Maharashtra" },
        { id: 20, name: "MANIT Bhopal", location: "Bhopal", state: "Madhya Pradesh", type: "NIT", nirf: 70, naac: "A", established: 1960, annualFees: "₹95,000", entrance: "JEE Main", topBranches: ["CSE", "IT", "ECE"], avgPackage: "6–10 LPA", topRecruiters: "Infosys, TCS, Wipro", website: "manit.ac.in", highlight: "🌿 Best NIT in MP. Most affordable NIT" },
        { id: 21, name: "MNNIT Allahabad", location: "Prayagraj", state: "Uttar Pradesh", type: "NIT", nirf: 57, naac: "A+", established: 1961, annualFees: "₹1,00,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "IT"], avgPackage: "7–12 LPA", website: "mnnit.ac.in", highlight: "📚 Strong academics in North India" },
        { id: 22, name: "NIT Jamshedpur", location: "Jamshedpur", state: "Jharkhand", type: "NIT", nirf: 61, established: 1960, annualFees: "₹1,05,000", entrance: "JEE Main", topBranches: ["CSE", "Mechanical", "Production"], avgPackage: "6–11 LPA", website: "nitjsr.ac.in", highlight: "⚙️ Industrial city advantage" },
        { id: 23, name: "NIT Kurukshetra", location: "Kurukshetra", state: "Haryana", type: "NIT", nirf: 59, established: 1963, annualFees: "₹1,10,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "Electrical"], avgPackage: "6–11 LPA", website: "nitkkr.ac.in", highlight: "🏙️ Near Delhi-NCR tech hub" },
        { id: 24, name: "NIT Durgapur", location: "Durgapur", state: "West Bengal", type: "NIT", nirf: 53, established: 1960, annualFees: "₹1,05,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "Chemical"], avgPackage: "6–10 LPA", website: "nitdgp.ac.in", highlight: "🏭 Industrial belt advantage" },
        { id: 25, name: "NIT Silchar", location: "Silchar", state: "Assam", type: "NIT", nirf: 75, established: 1967, annualFees: "₹90,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "Civil"], avgPackage: "5–9 LPA", website: "nits.ac.in", highlight: "🌿 Best NIT in Northeast" },
        { id: 26, name: "NIT Hamirpur", location: "Hamirpur", state: "Himachal Pradesh", type: "NIT", nirf: 66, established: 1986, annualFees: "₹1,00,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "Mechanical"], avgPackage: "5–9 LPA", website: "nith.ac.in", highlight: "🏔️ Scenic Himalayan campus" }
    ],
    iiits: [
        { id: 27, name: "IIIT Hyderabad", location: "Hyderabad", state: "Telangana", type: "IIIT", nirf: 30, established: 1998, annualFees: "₹3,10,000", entrance: "JEE Main / UGEE", topBranches: ["CSE", "ECE", "Data Science"], avgPackage: "₹15–25 LPA", topRecruiters: "Google, Microsoft, Amazon", website: "iiit.ac.in", highlight: "🤖 Best IIIT in India for Research" },
        { id: 28, name: "IIIT Bangalore", location: "Bengaluru", state: "Karnataka", type: "IIIT", nirf: 35, established: 1999, annualFees: "₹4,50,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "IT"], avgPackage: "14–22 LPA", website: "iiitb.ac.in", highlight: "💼 Bengaluru location - Best for IT" },
        { id: 29, name: "IIIT Allahabad", location: "Prayagraj", state: "Uttar Pradesh", type: "IIIT", nirf: 48, established: 1999, annualFees: "₹1,60,000", entrance: "JEE Main", topBranches: ["IT", "ECE"], avgPackage: "10–18 LPA", website: "iiita.ac.in", highlight: "💻 Excellent coding culture" },
        { id: 30, name: "ABV-IIITM Gwalior", location: "Gwalior", state: "Madhya Pradesh", type: "IIIT", nirf: 56, established: 1997, annualFees: "₹1,10,000", entrance: "JEE Main", topBranches: ["IT", "ECE", "Integrated MBA"], avgPackage: "8–14 LPA", topRecruiters: "TCS, Amazon, Wipro", website: "iiitm.ac.in", highlight: "🌟 IIIT in MP! Excellent IT placements" }
    ],
    private: [
        { id: 31, name: "BITS Pilani", location: "Pilani", state: "Rajasthan", type: "Private", nirf: 25, annualFees: "₹5,20,000", entrance: "BITSAT", topBranches: ["CSE", "Electrical", "Mechanical"], avgPackage: "₹18-25 LPA", website: "bits-pilani.ac.in", highlight: "💎 Premium private university. No JEE needed" },
        { id: 39, name: "VIT Vellore", location: "Vellore", state: "Tamil Nadu", type: "Private", nirf: 11, naac: "A++", established: 1984, annualFees: "₹1,98,000", entrance: "VITEEE", topBranches: ["CSE", "ECE", "Mechanical"], avgPackage: "₹6–12 LPA", topRecruiters: "Cognizant, TCS, Amazon", website: "vit.ac.in", highlight: "🚀 Top private university in India" },
        { id: 41, name: "Manipal Institute of Tech", location: "Manipal", state: "Karnataka", type: "Private", nirf: 49, established: 1957, annualFees: "₹3,20,000", entrance: "MET", topBranches: ["CSE", "IT", "Aeronautical"], avgPackage: "7–13 LPA", website: "manipal.edu", highlight: "💎 Premium infrastructure & culture" },
        { id: 42, name: "KIIT University", location: "Bhubaneswar", state: "Odisha", type: "Private", nirf: 17, annualFees: "₹3,50,000", entrance: "KIITEE", topBranches: ["CSE", "IT", "Mechanical"], avgPackage: "6–11 LPA", website: "kiit.ac.in", highlight: "🌳 Beautiful campus. High scholarships" },
        { id: 61, name: "Acropolis Institute of Technology", location: "Indore", state: "Madhya Pradesh", type: "Private", naac: "B++", established: 2004, annualFees: "₹85,000", entrance: "MP DTE / JEE", topBranches: ["CSE", "IT", "Civil"], avgPackage: "3–6 LPA", topRecruiters: "Persistent, TCS, HCL", website: "acropolis.in", highlight: "🌟 Top Private in Indore. NBA Accredited." },
        { id: 57, name: "Medi-Caps University", location: "Indore", state: "Madhya Pradesh", type: "Private", established: 2000, annualFees: "₹95,000", entrance: "MP DTE / JEE", topBranches: ["CSE", "IT", "Mechanical"], avgPackage: "3.5–6 LPA", website: "medicaps.ac.in", highlight: "📚 Popular private choice in Indore" },
        { id: 55, name: "LNCT Bhopal", location: "Bhopal", state: "Madhya Pradesh", type: "Private", established: 1994, annualFees: "₹85,000", entrance: "MP DTE / JEE", topBranches: ["CSE", "ECE", "IT"], avgPackage: "3–6 LPA", website: "lnct.ac.in", highlight: "🏫 Largest private group in Central India" },
        { id: 38, name: "Thapar Institute", location: "Patiala", state: "Punjab", type: "Private", nirf: 41, established: 1956, annualFees: "₹3,80,000", entrance: "JEE Main", topBranches: ["CSE", "ECE", "Mechanical"], avgPackage: "8–15 LPA", website: "thapar.edu", highlight: "🔬 Research focus. Strong placements" },
        { id: 43, name: "Chandigarh University", location: "Mohali", state: "Punjab", type: "Private", nirf: 32, annualFees: "₹1,80,000", entrance: "CUCET", topBranches: ["CSE", "IT", "Mechanical"], avgPackage: "5–8 LPA", website: "cuchd.in", highlight: "💰 High volume placements records" },
        { id: 44, name: "LPU Jalandhar", location: "Phagwara", state: "Punjab", type: "Private", nirf: 44, annualFees: "₹2,10,000", entrance: "LPUNEST", topBranches: ["CSE", "IT", "AI"], avgPackage: "4–8 LPA", website: "lpu.in", highlight: "💡 Massive campus & diversity" },
        { id: 45, name: "Amity Noida", location: "Noida", state: "Uttar Pradesh", type: "Private", nirf: 55, annualFees: "₹2,40,000", entrance: "Amity Exam / JEE", topBranches: ["CSE", "ECE", "AI"], avgPackage: "5–9 LPA", website: "amity.edu", highlight: "🏙️ Great NCR location & networking" }
    ],
    stateGovt: [
        { id: 32, name: "DTU Delhi", location: "New Delhi", state: "Delhi", type: "State Govt", nirf: 45, annualFees: "₹1,80,000", entrance: "JEE Main", topBranches: ["CSE", "IT", "Mechanical"], avgPackage: "8–15 LPA", website: "dtu.ac.in", highlight: "🏙️ Top state college in Delhi" },
        { id: 33, name: "NSUT Delhi", location: "New Delhi", state: "Delhi", type: "State Govt", nirf: 55, annualFees: "₹1,70,000", entrance: "JEE Main", topBranches: ["CSE", "IT", "ECE"], avgPackage: "7–13 LPA", website: "nsut.ac.in", highlight: "🏙️ Excellent tech placements in Delhi" },
        { id: 34, name: "COEP Pune", location: "Pune", state: "Maharashtra", type: "State Govt", nirf: 55, naac: "A++", established: 1854, annualFees: "₹1,20,000", entrance: "MHT-CET", topBranches: ["CSE", "Mechanical", "Civil"], avgPackage: "7–14 LPA", website: "coeptech.ac.in", highlight: "🏛️ Asia's oldest engineering college" },
        { id: 35, name: "VJTI Mumbai", location: "Mumbai", state: "Maharashtra", type: "State Govt", nirf: 62, established: 1887, annualFees: "₹1,20,000", entrance: "MHT-CET", topBranches: ["CSE", "IT", "Mechanical"], avgPackage: "7–14 LPA", website: "vjti.ac.in", highlight: "🌆 Mumbai location advantage" },
        { id: 56, name: "RGPV Bhopal", location: "Bhopal", state: "Madhya Pradesh", type: "State Govt", annualFees: "₹65,000", entrance: "MP DTE / JEE", topBranches: ["CSE", "Mechanical", "Civil"], avgPackage: "3–5 LPA", website: "rgpv.ac.in", highlight: "💰 Affordable Govt B.Tech in MP" },
        { id: 121, name: "HBTU Kanpur", location: "Kanpur", state: "Uttar Pradesh", type: "State Govt", established: 1921, annualFees: "₹80,000", entrance: "JEE Main", topBranches: ["CSE", "Chemical", "Mechanical"], avgPackage: "4–8 LPA", website: "hbtu.ac.in", highlight: "💰 Academic excellence at low cost" }
    ]
};

// ════════════════════════════════════════════════
// FLATTEN DATA TO MAIN COLLECTION
// ════════════════════════════════════════════════
const COLLEGES_DATA = [];

function cleanPrice(price) {
    if (typeof price === 'number') return price;
    return parseInt(price.replace(/[^\d]/g, '')) || 0;
}

Object.keys(BTECH_COLLEGES).forEach(category => {
    BTECH_COLLEGES[category].forEach(c => {
        const annualFees = cleanPrice(c.annualFees);
        const totalFees = cleanPrice(c.totalFees4yr || (annualFees * 4));

        COLLEGES_DATA.push({
            id: c.id ? c.id.toString() : c.name.toLowerCase().replace(/ /g, '-'),
            name: c.name,
            location: c.location.split(',')[0],
            state: c.state,
            type: (c.type === 'Private' || c.type === 'Deemed Private') ? 'Private' : 'Government',
            nirf: c.nirf || 999,
            fees_annual: annualFees,
            fees_total: totalFees,
            entrance: c.entrance || "JEE Main",
            duration: "4 Years",
            package: c.avgPackage || "N/A",
            naac: c.naac || "B",
            highlight: c.highlight || "",
            course: "B.Tech",
            isIIT: c.type === "IIT",
            isNIT: c.type === "NIT",
            isMP: c.state === "Madhya Pradesh",
            isGovernment: (c.type !== 'Private' && c.type !== 'Deemed Private'),
            extra: {
                branches: c.topBranches || [],
                scholarships: c.scholarship ? [c.scholarship] : ["Merit Cum Means", "State Scholarship"],
                companies: c.topRecruiters ? c.topRecruiters.split(',').map(s => s.trim()) : ["TCS", "Infosys", "Wipro"],
                website: c.website ? (c.website.startsWith('http') ? c.website : "https://" + c.website) : "#",
                breakdown: { tuition: annualFees, hostel: 0, other: 0 }
            }
        });
    });
});


// ════════════════════════════════════════════════
// NON-BTECH COLLEGES (MBBS, B.Sc CS, B.Com, BBA, B.A., Law, B.Ed)
// ════════════════════════════════════════════════

const OTHER_COLLEGES_RAW = [
  // ── MBBS ──
  { id:"mbbs-001", name:"AIIMS New Delhi",            location:"New Delhi",   state:"Delhi",              type:"Government", nirf:1,   fees_annual:1628,    fees_total:9768,     entrance:"NEET UG",  duration:"5.5 Years", package:"₹12–20 LPA", naac:"A++", highlight:"🥇 Best medical college in India. Almost FREE fees!",   course:"MBBS", isGovernment:true,  isMP:false, specialties:["Cardiology","Neurology","Oncology"],        scholarship:"Full fee waiver for SC/ST. Merit scholarships.", placed:["Govt hospitals, Super-speciality hospitals"] },
  { id:"mbbs-002", name:"AIIMS Bhopal",               location:"Bhopal",      state:"Madhya Pradesh",     type:"Government", nirf:6,   fees_annual:1628,    fees_total:9768,     entrance:"NEET UG",  duration:"5.5 Years", package:"₹10–18 LPA", naac:"A+",  highlight:"🌿 AIIMS in MP! Best medical college in Madhya Pradesh",  course:"MBBS", isGovernment:true,  isMP:true,  specialties:["General Surgery","Pediatrics","Orthopedics"],scholarship:"Full fee waiver for SC/ST.",               placed:["Govt hospitals, MP Govt"] },
  { id:"mbbs-003", name:"AIIMS Jodhpur",              location:"Jodhpur",     state:"Rajasthan",          type:"Government", nirf:7,   fees_annual:1628,    fees_total:9768,     entrance:"NEET UG",  duration:"5.5 Years", package:"₹10–16 LPA", naac:"A+",  highlight:"🏜️ AIIMS Rajasthan. Excellent clinical exposure",          course:"MBBS", isGovernment:true,  isMP:false, specialties:["General Medicine","Surgery","Pediatrics"],  scholarship:"SC/ST full fee waiver.",                  placed:["Govt hospitals"] },
  { id:"mbbs-004", name:"Maulana Azad Medical College",location:"New Delhi",  state:"Delhi",              type:"Government", nirf:10,  fees_annual:10000,   fees_total:60000,    entrance:"NEET UG",  duration:"5.5 Years", package:"₹8–15 LPA",  naac:"A",   highlight:"🏛️ Best state govt medical college. Highest seats in Delhi",course:"MBBS", isGovernment:true,  isMP:false, specialties:["All major specialties"],                   scholarship:"Delhi Govt + NSP scholarships.",           placed:["Govt hospitals, Lok Nayak Hospital"] },
  { id:"mbbs-005", name:"Grant Medical College Mumbai",location:"Mumbai",     state:"Maharashtra",        type:"Government", nirf:12,  fees_annual:14000,   fees_total:77000,    entrance:"NEET UG",  duration:"5.5 Years", package:"₹8–15 LPA",  naac:"A",   highlight:"🌆 One of the oldest medical colleges in India (1845)",    course:"MBBS", isGovernment:true,  isMP:false, specialties:["General Medicine","Surgery"],               scholarship:"Maharashtra Govt scholarships.",           placed:["JJ Hospital, Govt hospitals"] },
  { id:"mbbs-006", name:"Gandhi Medical College Bhopal",location:"Bhopal",   state:"Madhya Pradesh",     type:"Government", nirf:null,fees_annual:16000,   fees_total:88000,    entrance:"NEET UG",  duration:"5.5 Years", package:"₹6–12 LPA",  naac:"B+",  highlight:"🏥 Top govt medical college in MP after AIIMS Bhopal",     course:"MBBS", isGovernment:true,  isMP:true,  specialties:["General Medicine","Surgery","Pediatrics"],  scholarship:"MP Govt + NSP scholarships.",              placed:["Hamidia Hospital, MP Govt"] },
  { id:"mbbs-007", name:"Bangalore Medical College",   location:"Bengaluru",  state:"Karnataka",          type:"Government", nirf:null,fees_annual:32500,   fees_total:178750,   entrance:"NEET UG",  duration:"5.5 Years", package:"₹7–14 LPA",  naac:"A",   highlight:"⭐ Best govt medical in Karnataka. Attached to Victoria Hospital",course:"MBBS",isGovernment:true,isMP:false,specialties:["General Medicine","Surgery","Dermatology"],scholarship:"Karnataka Govt scholarships.",             placed:["Victoria Hospital, Govt hospitals"] },
  { id:"mbbs-008", name:"Stanley Medical College Chennai",location:"Chennai", state:"Tamil Nadu",         type:"Government", nirf:null,fees_annual:16000,   fees_total:88000,    entrance:"NEET UG",  duration:"5.5 Years", package:"₹6–12 LPA",  naac:"A",   highlight:"🌆 One of the oldest govt medical colleges in South India",  course:"MBBS", isGovernment:true,  isMP:false, specialties:["General Medicine","Surgery"],               scholarship:"TN Govt + merit scholarships.",            placed:["Govt hospitals TN"] },
  { id:"mbbs-009", name:"Lady Hardinge Medical College",location:"New Delhi", state:"Delhi",              type:"Government", nirf:15,  fees_annual:10000,   fees_total:60000,    entrance:"NEET UG",  duration:"5.5 Years", package:"₹8–14 LPA",  naac:"A",   highlight:"👩 Women's medical college Delhi. Excellent government institution",course:"MBBS",isGovernment:true,isMP:false,specialties:["Obs & Gynae","Pediatrics"],               scholarship:"Delhi Govt scholarships.",                  placed:["Delhi Govt hospitals"] },
  { id:"mbbs-010", name:"Seth GS Medical College Mumbai",location:"Mumbai",  state:"Maharashtra",        type:"Government", nirf:8,   fees_annual:14000,   fees_total:77000,    entrance:"NEET UG",  duration:"5.5 Years", package:"₹8–16 LPA",  naac:"A",   highlight:"🏥 NIRF Top 10 medical. Attached to KEM Hospital",          course:"MBBS", isGovernment:true,  isMP:false, specialties:["All major specialties"],                   scholarship:"Maharashtra Govt scholarships.",           placed:["KEM Hospital, Govt hospitals"] },
  { id:"mbbs-011", name:"Kasturba Medical College Manipal",location:"Manipal",state:"Karnataka",         type:"Private",    nirf:4,   fees_annual:1500000, fees_total:9000000,  entrance:"NEET UG",  duration:"5.5 Years", package:"₹10–18 LPA", naac:"A++", highlight:"⭐ NIRF Rank 4 private medical. Best private MBBS in India",  course:"MBBS", isGovernment:false, isMP:false, specialties:["All super-specialties","Research"],         scholarship:"Merit scholarships for NEET top scorers.",  placed:["Private hospitals, Super-specialty"] },
  { id:"mbbs-012", name:"Amrita Medical Sciences Kochi",location:"Kochi",    state:"Kerala",             type:"Private",    nirf:5,   fees_annual:1350000, fees_total:8100000,  entrance:"NEET UG",  duration:"5.5 Years", package:"₹8–15 LPA",  naac:"A++", highlight:"🌴 NIRF Rank 5. Best private medical in Kerala",            course:"MBBS", isGovernment:false, isMP:false, specialties:["Cardiology","Neurology","Oncology"],        scholarship:"NEET merit scholarships.",                 placed:["Amrita hospitals, Private hospitals"] },
  { id:"mbbs-013", name:"Sri Ramachandra Institute Chennai",location:"Chennai",state:"Tamil Nadu",       type:"Private",    nirf:12,  fees_annual:1150000, fees_total:6900000,  entrance:"NEET UG",  duration:"5.5 Years", package:"₹7–13 LPA",  naac:"A++", highlight:"🌆 Top private in South India. Good research output",        course:"MBBS", isGovernment:false, isMP:false, specialties:["Multi-specialty hospital"],                scholarship:"Merit-cum-means scholarships.",            placed:["Private hospitals South India"] },
  { id:"mbbs-014", name:"DY Patil Medical College Pune",location:"Pune",     state:"Maharashtra",        type:"Private",    nirf:null,fees_annual:1250000, fees_total:7500000,  entrance:"NEET UG",  duration:"5.5 Years", package:"₹6–12 LPA",  naac:"A",   highlight:"🏙️ Well-known private medical in Pune. DY Patil group",     course:"MBBS", isGovernment:false, isMP:false, specialties:["General Medicine","Surgery"],               scholarship:"Merit scholarships.",                      placed:["DY Patil hospitals, Private hospitals"] },
  { id:"mbbs-015", name:"People's Medical College Bhopal",location:"Bhopal", state:"Madhya Pradesh",     type:"Private",    nirf:null,fees_annual:900000,  fees_total:5400000,  entrance:"NEET UG",  duration:"5.5 Years", package:"₹5–10 LPA",  naac:"B+",  highlight:"🏥 Most affordable private MBBS in MP",                     course:"MBBS", isGovernment:false, isMP:true,  specialties:["General Medicine","Surgery"],               scholarship:"MP Govt scholarships for SC/ST.",           placed:["People's College hospital, Private hospitals"] },

  // ── B.Sc CS ──
  { id:"bsccs-001", name:"St. Stephen's College Delhi",  location:"New Delhi",  state:"Delhi",           type:"Government", nirf:8,   fees_annual:16000,   fees_total:48000,    entrance:"CUET UG",  duration:"3 Years", package:"₹6–12 LPA",  naac:"A++", highlight:"🏛️ Most prestigious B.Sc CS in India. DU top college",    course:"B.Sc CS", isGovernment:true, isMP:false, specialties:["Computer Science"],   scholarship:"DU + merit scholarships.",           placed:["Google, Microsoft, Amazon, TCS, Infosys"] },
  { id:"bsccs-002", name:"Hansraj College Delhi",         location:"New Delhi",  state:"Delhi",           type:"Government", nirf:18,  fees_annual:14000,   fees_total:42000,    entrance:"CUET UG",  duration:"3 Years", package:"₹5–10 LPA",  naac:"A++", highlight:"⭐ Top DU college for B.Sc CS. Strong alumni in tech",      course:"B.Sc CS", isGovernment:true, isMP:false, specialties:["Computer Science"],   scholarship:"DU scholarships.",                   placed:["Amazon, TCS, Wipro, Infosys, HCL"] },
  { id:"bsccs-003", name:"Miranda House Delhi",           location:"New Delhi",  state:"Delhi",           type:"Government", nirf:1,   fees_annual:12000,   fees_total:36000,    entrance:"CUET UG",  duration:"3 Years", package:"₹5–10 LPA",  naac:"A++", highlight:"👩 NIRF Rank 1 college in India! Women only — DU",         course:"B.Sc CS", isGovernment:true, isMP:false, specialties:["Computer Science"],   scholarship:"DU scholarships.",                   placed:["TCS, Infosys, Wipro, Amazon, Google"] },
  { id:"bsccs-004", name:"Presidency College Chennai",    location:"Chennai",    state:"Tamil Nadu",      type:"Government", nirf:28,  fees_annual:6500,    fees_total:19500,    entrance:"TN Merit",  duration:"3 Years", package:"₹3–7 LPA",   naac:"A++", highlight:"🌆 Best govt B.Sc CS in South India. Autonomous college",  course:"B.Sc CS", isGovernment:true, isMP:false, specialties:["Computer Science"],   scholarship:"TN Govt scholarships.",              placed:["TCS, Wipro, Infosys, CTS, HCL"] },
  { id:"bsccs-005", name:"Fergusson College Pune",        location:"Pune",       state:"Maharashtra",     type:"Government", nirf:35,  fees_annual:12500,   fees_total:37500,    entrance:"Direct merit",duration:"3 Years", package:"₹3–6 LPA",   naac:"A++", highlight:"🏛️ Most prestigious govt college in Pune. 140-year legacy", course:"B.Sc CS", isGovernment:true, isMP:false, specialties:["Computer Science"],   scholarship:"Maharashtra Govt scholarships.",     placed:["TCS, Wipro, Infosys, Capgemini"] },
  { id:"bsccs-006", name:"Holkar Science College Indore", location:"Indore",     state:"Madhya Pradesh",  type:"Government", nirf:null,fees_annual:4500,    fees_total:13500,    entrance:"MP DTE",   duration:"3 Years", package:"₹2–5 LPA",   naac:"A",   highlight:"🏫 Best govt science college in Indore. Very affordable",   course:"B.Sc CS", isGovernment:true, isMP:true,  specialties:["Computer Science"],   scholarship:"MP Govt scholarships. Medhavi Yojana.",placed:["TCS, Wipro, local IT companies"] },
  { id:"bsccs-007", name:"Govt Science College Bhopal",   location:"Bhopal",     state:"Madhya Pradesh",  type:"Government", nirf:null,fees_annual:3750,    fees_total:11250,    entrance:"MP DTE",   duration:"3 Years", package:"₹1.5–4 LPA", naac:"B+",  highlight:"💰 Most affordable B.Sc CS in Bhopal — under ₹5K/year",   course:"B.Sc CS", isGovernment:true, isMP:true,  specialties:["Computer Science"],   scholarship:"MP Govt scholarships.",              placed:["Local companies, TCS, HCL"] },
  { id:"bsccs-008", name:"Ramjas College Delhi",          location:"New Delhi",  state:"Delhi",           type:"Government", nirf:null,fees_annual:14000,   fees_total:42000,    entrance:"CUET UG",  duration:"3 Years", package:"₹4–8 LPA",   naac:"A+",  highlight:"📚 Good DU college. Strong CS department",                 course:"B.Sc CS", isGovernment:true, isMP:false, specialties:["Computer Science"],   scholarship:"DU scholarships.",                   placed:["TCS, Infosys, HCL, Wipro"] },
  { id:"bsccs-009", name:"Christ University Bengaluru",   location:"Bengaluru",  state:"Karnataka",       type:"Private",    nirf:42,  fees_annual:140000,  fees_total:420000,   entrance:"Christ Entrance",duration:"3 Years", package:"₹4–8 LPA",   naac:"A++", highlight:"🌆 Best private B.Sc CS in Bengaluru. IT city advantage",  course:"B.Sc CS", isGovernment:false,isMP:false, specialties:["Computer Science"],   scholarship:"Merit scholarships 10–50%.",         placed:["Amazon, TCS, Infosys, Wipro, Accenture"] },
  { id:"bsccs-010", name:"Loyola College Chennai",        location:"Chennai",    state:"Tamil Nadu",      type:"Private",    nirf:32,  fees_annual:32500,   fees_total:97500,    entrance:"Merit-based",duration:"3 Years", package:"₹3–7 LPA",   naac:"A++", highlight:"⭐ NAAC A++ autonomous. Best private science college Chennai",course:"B.Sc CS",isGovernment:false,isMP:false,specialties:["Computer Science"],  scholarship:"Merit + need-based scholarships.",   placed:["TCS, Wipro, CTS, Infosys, HCL"] },
  { id:"bsccs-011", name:"SICSR Pune",                    location:"Pune",       state:"Maharashtra",     type:"Private",    nirf:null,fees_annual:100000,  fees_total:300000,   entrance:"SET",      duration:"3 Years", package:"₹4–8 LPA",   naac:"A",   highlight:"🎓 Symbiosis brand. Good Pune IT industry connects",        course:"B.Sc CS", isGovernment:false,isMP:false, specialties:["Computer Science","IT"],scholarship:"SET score-based scholarships.",       placed:["TCS, Wipro, Infosys, Capgemini, Accenture"] },
  { id:"bsccs-012", name:"BITS Pilani — B.Sc CS",         location:"Pilani",     state:"Rajasthan",       type:"Private",    nirf:28,  fees_annual:475000,  fees_total:1425000,  entrance:"BITSAT",   duration:"3 Years", package:"₹10–18 LPA", naac:"A",   highlight:"🚀 BITS B.Sc CS = IIT-equivalent placements",             course:"B.Sc CS", isGovernment:false,isMP:false, specialties:["Computer Science"],   scholarship:"Merit-cum-means scholarships.",      placed:["Google, Microsoft, Goldman Sachs, Amazon, Qualcomm"] },

  // ── B.Com ──
  { id:"bcom-001", name:"SRCC Delhi",               location:"New Delhi",  state:"Delhi",           type:"Government", nirf:1,   fees_annual:17500,   fees_total:52500,    entrance:"CUET UG",  duration:"3 Years", package:"₹8–15 LPA",  naac:"A++", highlight:"🥇 #1 B.Com college India. Gateway to top MBAs",          course:"B.Com", isGovernment:true, isMP:false, specialties:["Commerce","Finance"],     scholarship:"DU + merit scholarships.",           placed:["Goldman Sachs, EY, Deloitte, KPMG, McKinsey"] },
  { id:"bcom-002", name:"Hindu College Delhi",       location:"New Delhi",  state:"Delhi",           type:"Government", nirf:5,   fees_annual:15000,   fees_total:45000,    entrance:"CUET UG",  duration:"3 Years", package:"₹6–12 LPA",  naac:"A++", highlight:"🏛️ Top DU college. Strong finance + CA pathway",           course:"B.Com", isGovernment:true, isMP:false, specialties:["Commerce","Economics"],   scholarship:"DU scholarships.",                   placed:["Big 4 firms, ICICI, HDFC, TCS"] },
  { id:"bcom-003", name:"Loyola College Chennai (B.Com)",location:"Chennai",state:"Tamil Nadu",      type:"Private",    nirf:15,  fees_annual:27500,   fees_total:82500,    entrance:"Merit-based",duration:"3 Years", package:"₹3–6 LPA",   naac:"A++", highlight:"⭐ Best private B.Com South India. NAAC A++",             course:"B.Com", isGovernment:false,isMP:false, specialties:["Commerce"],               scholarship:"Need-based + merit scholarships.",   placed:["TCS, Wipro, Big 4, ICICI Bank"] },
  { id:"bcom-004", name:"Nizam College Hyderabad",   location:"Hyderabad",  state:"Telangana",       type:"Government", nirf:null,fees_annual:11000,   fees_total:33000,    entrance:"TS DOST",  duration:"3 Years", package:"₹2.5–5 LPA", naac:"A+",  highlight:"🏛️ Oldest govt college in Hyderabad (1887). NAAC A+",       course:"B.Com", isGovernment:true, isMP:false, specialties:["Commerce","Accounting"],  scholarship:"TS Govt + merit scholarships.",      placed:["Big 4, Banks, IT companies"] },
  { id:"bcom-005", name:"Govt Commerce College Bhopal",location:"Bhopal",  state:"Madhya Pradesh",  type:"Government", nirf:null,fees_annual:3750,    fees_total:11250,    entrance:"MP DTE",   duration:"3 Years", package:"₹1.5–3.5 LPA",naac:"B+",highlight:"💰 Most affordable B.Com in Bhopal. Under ₹5K/year",      course:"B.Com", isGovernment:true, isMP:true,  specialties:["Commerce","Accounting"],  scholarship:"MP Govt scholarships. Gaon Ki Beti.",placed:["Local CA firms, banks, TCS"] },
  { id:"bcom-006", name:"Lady Shri Ram College Delhi",location:"New Delhi", state:"Delhi",           type:"Government", nirf:5,   fees_annual:13000,   fees_total:39000,    entrance:"CUET UG",  duration:"3 Years", package:"₹5–10 LPA",  naac:"A++", highlight:"👩 Top women's college DU. Strong finance career outcomes",  course:"B.Com", isGovernment:true, isMP:false, specialties:["Commerce","Finance"],     scholarship:"DU scholarships.",                   placed:["EY, Deloitte, KPMG, HDFC, ICICI"] },
  { id:"bcom-007", name:"Christ University Bengaluru (B.Com)",location:"Bengaluru",state:"Karnataka",type:"Private",   nirf:38,  fees_annual:107500,  fees_total:322500,   entrance:"Christ Entrance",duration:"3 Years", package:"₹3–7 LPA",   naac:"A++", highlight:"🌆 Best private B.Com in Bangalore. Finance + tech",        course:"B.Com", isGovernment:false,isMP:false, specialties:["Commerce","Finance"],     scholarship:"Merit scholarships.",                placed:["Deloitte, EY, TCS, HDFC Bank, Amazon"] },
  { id:"bcom-008", name:"Symbiosis College Pune",    location:"Pune",       state:"Maharashtra",     type:"Private",    nirf:null,fees_annual:82500,   fees_total:247500,   entrance:"SET",      duration:"3 Years", package:"₹3–6 LPA",   naac:"A",   highlight:"🎓 Symbiosis brand. Good Pune finance + CA pathway",        course:"B.Com", isGovernment:false,isMP:false, specialties:["Commerce"],               scholarship:"SET merit scholarships.",            placed:["KPMG, Deloitte, HDFC, ICICI, TCS"] },
  { id:"bcom-009", name:"Jain University Bengaluru", location:"Bengaluru",  state:"Karnataka",       type:"Private",    nirf:null,fees_annual:97500,   fees_total:292500,   entrance:"Direct",   duration:"3 Years", package:"₹3–6 LPA",   naac:"A++", highlight:"🌆 Good Bangalore private. Multiple B.Com specializations", course:"B.Com", isGovernment:false,isMP:false, specialties:["Commerce","Banking"],    scholarship:"Merit scholarships.",                placed:["Deloitte, KPMG, HDFC Bank, Infosys"] },
  { id:"bcom-010", name:"NMIMS Mumbai (Commerce)",  location:"Mumbai",      state:"Maharashtra",     type:"Private",    nirf:null,fees_annual:180000,  fees_total:540000,   entrance:"NPAT",     duration:"3 Years", package:"₹5–10 LPA",  naac:"A",   highlight:"💎 Premium Mumbai B.Com. Finance capital advantage",        course:"B.Com", isGovernment:false,isMP:false, specialties:["Commerce","Finance"],     scholarship:"Merit scholarships.",                placed:["Goldman Sachs, JP Morgan, HDFC, ICICI, Deloitte"] },

  // ── BBA ──
  { id:"bba-001", name:"IIM Indore — IPM",      location:"Indore",     state:"Madhya Pradesh",  type:"Government", nirf:7,   fees_annual:475000,  fees_total:2375000,  entrance:"IPMAT",    duration:"5 Years", package:"₹18–25 LPA", naac:"A++", highlight:"🥇 Best BBA program India. IIM degree at the end!",    course:"BBA", isGovernment:true, isMP:true,  specialties:["Management","Finance"],   scholarship:"Merit-cum-means. SC/ST fee reduction.",placed:["McKinsey, BCG, Goldman Sachs, Amazon, Google"] },
  { id:"bba-002", name:"IIM Rohtak — IPM",      location:"Rohtak",     state:"Haryana",         type:"Government", nirf:10,  fees_annual:375000,  fees_total:1875000,  entrance:"IPMAT",    duration:"5 Years", package:"₹14–20 LPA", naac:"A+",  highlight:"🏛️ IIM Rohtak. Second best IIM IPM program",           course:"BBA", isGovernment:true, isMP:false, specialties:["Management"],              scholarship:"SC/ST fee reduction.",               placed:["BCG, Amazon, HUL, Infosys, Deloitte"] },
  { id:"bba-003", name:"IIM Ranchi — BBA",      location:"Ranchi",     state:"Jharkhand",       type:"Government", nirf:15,  fees_annual:325000,  fees_total:975000,   entrance:"JIPMAT",   duration:"3 Years", package:"₹8–14 LPA",  naac:"A",   highlight:"🏛️ IIM Ranchi BBA. IIM brand + affordable option",     course:"BBA", isGovernment:true, isMP:false, specialties:["Management","HR"],         scholarship:"Need-based scholarships.",           placed:["TATA, Amazon, Deloitte, KPMG, HCL"] },
  { id:"bba-004", name:"DU BMS",                location:"New Delhi",  state:"Delhi",           type:"Government", nirf:null,fees_annual:25000,   fees_total:75000,    entrance:"CUET UG",  duration:"3 Years", package:"₹5–10 LPA",  naac:"A++", highlight:"🏛️ DU BMS = Best affordable BBA in India. Delhi advantage",course:"BBA",isGovernment:true, isMP:false, specialties:["Management"],              scholarship:"DU + merit scholarships.",           placed:["EY, Deloitte, HDFC, Amazon, TCS"] },
  { id:"bba-005", name:"NMIMS Mumbai (BBA)",    location:"Mumbai",     state:"Maharashtra",     type:"Private",    nirf:null,fees_annual:385000,  fees_total:1155000,  entrance:"NPAT",     duration:"3 Years", package:"₹6–12 LPA",  naac:"A",   highlight:"💎 Best private BBA in Mumbai. Finance sector placement", course:"BBA", isGovernment:false,isMP:false, specialties:["Management","Finance"],   scholarship:"Merit scholarships.",                placed:["Goldman Sachs, JP Morgan, Deloitte, KPMG, HDFC"] },
  { id:"bba-006", name:"Christ University (BBA)",location:"Bengaluru",  state:"Karnataka",       type:"Private",    nirf:null,fees_annual:140000,  fees_total:420000,   entrance:"Christ Entrance",duration:"3 Years", package:"₹4–8 LPA",   naac:"A++", highlight:"🌆 Best private BBA in Bengaluru. Good MBA pathway",    course:"BBA", isGovernment:false,isMP:false, specialties:["Management"],              scholarship:"Merit scholarships.",                placed:["Amazon, Flipkart, Deloitte, TCS, HDFC"] },
  { id:"bba-007", name:"SCMS Pune",             location:"Pune",       state:"Maharashtra",     type:"Private",    nirf:null,fees_annual:250000,  fees_total:750000,   entrance:"SET",      duration:"3 Years", package:"₹5–9 LPA",   naac:"A",   highlight:"🎓 Symbiosis BBA = Premium Pune management education",  course:"BBA", isGovernment:false,isMP:false, specialties:["Management"],              scholarship:"SET merit scholarships.",            placed:["Deloitte, KPMG, Wipro, TCS, Capgemini"] },
  { id:"bba-008", name:"Amity University Noida (BBA)",location:"Noida",state:"Uttar Pradesh",  type:"Private",    nirf:null,fees_annual:170000,  fees_total:510000,   entrance:"Direct",   duration:"3 Years", package:"₹4–7 LPA",   naac:"A+",  highlight:"🏙️ Amity brand. Good Delhi-NCR industry connections",   course:"BBA", isGovernment:false,isMP:false, specialties:["Management"],              scholarship:"Merit scholarships 10–50%.",         placed:["TCS, Infosys, HDFC, ICICI, Wipro"] },
  { id:"bba-009", name:"Chandigarh University (BBA)",location:"Mohali",state:"Punjab",          type:"Private",    nirf:null,fees_annual:105000,  fees_total:315000,   entrance:"CUCET",    duration:"3 Years", package:"₹3–6 LPA",   naac:"A+",  highlight:"💰 Affordable BBA. Good placement record",             course:"BBA", isGovernment:false,isMP:false, specialties:["Management"],              scholarship:"CUCET merit scholarships.",          placed:["TCS, Wipro, HDFC, ICICI, Capgemini"] },
  { id:"bba-010", name:"Prestige Institute Gwalior",location:"Gwalior", state:"Madhya Pradesh",  type:"Private",    nirf:null,fees_annual:92500,   fees_total:277500,   entrance:"Direct",   duration:"3 Years", package:"₹2.5–5 LPA", naac:"A",   highlight:"🏯 Best BBA in Gwalior. NAAC A. MP Govt scholarships eligible",course:"BBA",isGovernment:false,isMP:true,specialties:["Management"],             scholarship:"MP Govt + merit scholarships.",       placed:["HDFC, ICICI, TCS, local companies"] },

  // ── B.A. ──
  { id:"ba-001", name:"Miranda House Delhi (B.A.)", location:"New Delhi", state:"Delhi",          type:"Government", nirf:1,   fees_annual:12000,   fees_total:36000,    entrance:"CUET UG",  duration:"3 Years", package:"₹3–8 LPA",   naac:"A++", highlight:"🥇 NIRF Rank 1 college overall! Women only",              course:"B.A.", isGovernment:true, isMP:false, specialties:["Humanities","English","Economics"],scholarship:"DU scholarships.",                  placed:["UPSC toppers, Media, NGOs, MNCs, Banks"] },
  { id:"ba-002", name:"Lady Shri Ram College (B.A.)",location:"New Delhi",state:"Delhi",          type:"Government", nirf:5,   fees_annual:13000,   fees_total:39000,    entrance:"CUET UG",  duration:"3 Years", package:"₹4–9 LPA",   naac:"A++", highlight:"👩 Best women's college for B.A. Economics in India",      course:"B.A.", isGovernment:true, isMP:false, specialties:["Economics","Journalism"],         scholarship:"DU + merit scholarships.",          placed:["IAS/IPS, Media houses, MNCs, NGOs, Banks"] },
  { id:"ba-003", name:"St. Stephen's College (B.A.)",location:"New Delhi",state:"Delhi",          type:"Government", nirf:8,   fees_annual:16000,   fees_total:48000,    entrance:"CUET UG",  duration:"3 Years", package:"₹4–10 LPA",  naac:"A++", highlight:"🏛️ Most prestigious humanities college in India",          course:"B.A.", isGovernment:true, isMP:false, specialties:["English","History","Economics"],  scholarship:"DU + merit scholarships.",          placed:["UPSC toppers, Media, Big Firms, Civil Services"] },
  { id:"ba-004", name:"Presidency College Kolkata",  location:"Kolkata",  state:"West Bengal",     type:"Government", nirf:22,  fees_annual:7500,    fees_total:22500,    entrance:"WB Merit", duration:"3 Years", package:"₹3–7 LPA",   naac:"A",   highlight:"🏛️ Oldest college in East India (1817)",                  course:"B.A.", isGovernment:true, isMP:false, specialties:["Economics","English","History"],  scholarship:"WB Govt + merit scholarships.",     placed:["Civil Services, Media, Academics, MNCs"] },
  { id:"ba-005", name:"Fergusson College Pune (B.A.)",location:"Pune",   state:"Maharashtra",     type:"Government", nirf:35,  fees_annual:11000,   fees_total:33000,    entrance:"Direct",   duration:"3 Years", package:"₹2.5–6 LPA", naac:"A++", highlight:"🏛️ Best B.A. college in Maharashtra. 140-year legacy",    course:"B.A.", isGovernment:true, isMP:false, specialties:["Sociology","Psychology","Economics"],scholarship:"Maharashtra Govt scholarships.",   placed:["Civil Services, Media, NGOs, Banks"] },
  { id:"ba-006", name:"Govt Girls PG College Bhopal",location:"Bhopal",  state:"Madhya Pradesh",  type:"Government", nirf:null,fees_annual:3000,    fees_total:9000,     entrance:"Direct",   duration:"3 Years", package:"₹1.5–3.5 LPA",naac:"B+",highlight:"👩 Women only. Most affordable B.A. in Bhopal",           course:"B.A.", isGovernment:true, isMP:true,  specialties:["Hindi","History","Political Science"],scholarship:"MP Govt. Gaon Ki Beti. Pratibha Kiran.",placed:["Teaching, Banking, Govt jobs, UPSC"] },
  { id:"ba-007", name:"Christ University (B.A.)",    location:"Bengaluru",state:"Karnataka",       type:"Private",    nirf:null,fees_annual:95000,   fees_total:285000,   entrance:"Christ Entrance",duration:"3 Years", package:"₹3–6 LPA",   naac:"A++", highlight:"🌆 Best private B.A. in Bengaluru. Media + NGO connects",  course:"B.A.", isGovernment:false,isMP:false, specialties:["Psychology","Journalism","Pol.Sci"],scholarship:"Merit scholarships.",              placed:["Media houses, NGOs, MNCs, Banks"] },
  { id:"ba-008", name:"Ashoka University Sonipat",   location:"Sonipat",  state:"Haryana",         type:"Private",    nirf:18,  fees_annual:675000,  fees_total:2025000,  entrance:"Ashoka Entrance",duration:"3 Years", package:"₹7–14 LPA",  naac:"A",   highlight:"🌟 India's only true Liberal Arts university. US-style",   course:"B.A.", isGovernment:false,isMP:false, specialties:["Liberal Arts","Economics","Psychology"],scholarship:"Need-based scholarships up to 100%.",placed:["BCG, McKinsey, Amazon, Google, Goldman Sachs"] },
  { id:"ba-009", name:"FLAME University Pune",       location:"Pune",     state:"Maharashtra",     type:"Private",    nirf:null,fees_annual:550000,  fees_total:1650000,  entrance:"FLAME Test",duration:"3 Years", package:"₹5–10 LPA",  naac:"A",   highlight:"🎨 Liberal arts. Creativity + critical thinking focus",    course:"B.A.", isGovernment:false,isMP:false, specialties:["Liberal Arts"],                  scholarship:"Need + merit scholarships.",        placed:["Media, Consulting, NGOs, MNCs"] },

  // ── LAW ──
  { id:"law-001", name:"NLSIU Bangalore",      location:"Bengaluru",  state:"Karnataka",       type:"Government", nirf:1,   fees_annual:275000,  fees_total:1375000,  entrance:"CLAT",     duration:"5 Years", package:"₹12–20 LPA", naac:"A++", highlight:"🥇 #1 Law college India. NLSIU = Harvard of Indian law",  course:"Law", isGovernment:true, isMP:false, specialties:["Corporate Law","Litigation","IPR"], scholarship:"Need-based scholarships. SC/ST fee reduction.",placed:["Big Law Firms, UN, World Bank, Supreme Court"] },
  { id:"law-002", name:"NALSAR Hyderabad",     location:"Hyderabad",  state:"Telangana",       type:"Government", nirf:2,   fees_annual:200000,  fees_total:1000000,  entrance:"CLAT",     duration:"5 Years", package:"₹10–18 LPA", naac:"A++", highlight:"⭐ NIRF #2 law. Strong corporate law + litigation",        course:"Law", isGovernment:true, isMP:false, specialties:["Corporate Law","IPR"],              scholarship:"Need-based + merit scholarships.",   placed:["AZB, Cyril Amarchand, S&R Associates"] },
  { id:"law-003", name:"NLU Delhi",            location:"New Delhi",  state:"Delhi",           type:"Government", nirf:3,   fees_annual:225000,  fees_total:1125000,  entrance:"AILET",    duration:"5 Years", package:"₹12–20 LPA", naac:"A+",  highlight:"🏛️ Delhi NLU. AILET exam. Best for Delhi High Court",     course:"Law", isGovernment:true, isMP:false, specialties:["Constitutional Law","Corporate Law"],scholarship:"Need-based scholarships.",           placed:["AZB, Luthra & Luthra, Shardul Amarchand, SAM"] },
  { id:"law-004", name:"NUJS Kolkata",         location:"Kolkata",    state:"West Bengal",     type:"Government", nirf:5,   fees_annual:170000,  fees_total:850000,   entrance:"CLAT",     duration:"5 Years", package:"₹9–16 LPA",  naac:"A+",  highlight:"⭐ Top 5 NLU. Strong IPR and Corporate Law departments",  course:"Law", isGovernment:true, isMP:false, specialties:["IPR","Corporate Law"],              scholarship:"Merit + need-based scholarships.",   placed:["Big Law firms, Khaitan & Co, AZB"] },
  { id:"law-005", name:"NLU Jodhpur",          location:"Jodhpur",    state:"Rajasthan",       type:"Government", nirf:6,   fees_annual:180000,  fees_total:900000,   entrance:"CLAT",     duration:"5 Years", package:"₹8–14 LPA",  naac:"A+",  highlight:"🏜️ Good NLU in Rajasthan. Strong Moot Court culture",     course:"Law", isGovernment:true, isMP:false, specialties:["Corporate Law","Moot Court"],       scholarship:"SC/ST fee waiver + merit scholarships.", placed:["Big Law firms, Rajasthan HC"] },
  { id:"law-006", name:"Govt Law College Mumbai",location:"Mumbai",   state:"Maharashtra",     type:"Government", nirf:null,fees_annual:11500,   fees_total:69000,    entrance:"MH CET Law",duration:"5 Years", package:"₹4–10 LPA",  naac:"A",   highlight:"🌆 Oldest law college in Asia (1855). Mumbai HC proximity",course:"Law", isGovernment:true, isMP:false, specialties:["Litigation","Corporate Law"],      scholarship:"Maharashtra Govt scholarships.",     placed:["Mumbai HC, Corporate firms, Big Law"] },
  { id:"law-007", name:"Govt Law College Bhopal",location:"Bhopal",  state:"Madhya Pradesh",  type:"Government", nirf:null,fees_annual:7500,    fees_total:45000,    entrance:"MP CLAT",  duration:"5 Years", package:"₹2–5 LPA",   naac:"B+",  highlight:"💰 Most affordable law in MP. MP HC proximity advantage",  course:"Law", isGovernment:true, isMP:true,  specialties:["Litigation","MP HC Practice"],     scholarship:"MP Govt scholarships.",              placed:["MP High Court, District Courts, Govt jobs"] },
  { id:"law-008", name:"Symbiosis Law School Pune",location:"Pune",  state:"Maharashtra",     type:"Private",    nirf:12,  fees_annual:210000,  fees_total:1050000,  entrance:"CLAT/SLAT",duration:"5 Years", package:"₹6–12 LPA",  naac:"A",   highlight:"🏛️ Best private law school India. BBA LLB unique option", course:"Law", isGovernment:false,isMP:false, specialties:["BBA LLB","Corporate Law"],         scholarship:"SLAT merit scholarships.",           placed:["Big Law firms, Wipro, TCS, Corporates"] },
  { id:"law-009", name:"Amity Law School Noida",location:"Noida",    state:"Uttar Pradesh",   type:"Private",    nirf:null,fees_annual:175000,  fees_total:875000,   entrance:"CLAT",     duration:"5 Years", package:"₹4–8 LPA",   naac:"A",   highlight:"🏙️ Amity brand. Good Delhi-NCR court connections",        course:"Law", isGovernment:false,isMP:false, specialties:["Corporate Law","Litigation"],       scholarship:"Merit scholarships.",                placed:["Big Law firms, Corporate Legal teams"] },

  // ── B.Ed ──
  { id:"bed-001", name:"CIE Delhi University",    location:"New Delhi",  state:"Delhi",           type:"Government", nirf:3,   fees_annual:18500,   fees_total:37000,    entrance:"DU CET",   duration:"2 Years", package:"₹4–8 LPA",   naac:"A++", highlight:"🥇 Best B.Ed in India. Delhi University. CIE standard",  course:"B.Ed", isGovernment:true, isMP:false, specialties:["Education","Teacher Training"],   scholarship:"DU + merit scholarships.",           placed:["Delhi Govt Schools, KV, NVS, Private Schools"] },
  { id:"bed-002", name:"NCERT RIE Bhopal",        location:"Bhopal",     state:"Madhya Pradesh",  type:"Government", nirf:null,fees_annual:11500,   fees_total:23000,    entrance:"RIE CEE",  duration:"2 Years", package:"₹3–7 LPA",   naac:"A+",  highlight:"🌿 NCERT run institute in MP. Govt teaching jobs pathway", course:"B.Ed", isGovernment:true, isMP:true,  specialties:["Education","B.Sc B.Ed"],          scholarship:"NCERT scholarships. NSP.",           placed:["NVS, KV, MP Govt Schools, CBSE schools"] },
  { id:"bed-003", name:"NCERT RIE Mysuru",        location:"Mysuru",     state:"Karnataka",       type:"Government", nirf:null,fees_annual:11000,   fees_total:22000,    entrance:"RIE CEE",  duration:"2 Years", package:"₹3–6 LPA",   naac:"A",   highlight:"🌺 NCERT South India RIE. Best B.Ed in Karnataka region", course:"B.Ed", isGovernment:true, isMP:false, specialties:["Education","Teacher Training"],   scholarship:"NCERT scholarships.",               placed:["NVS, KV, Karnataka Govt Schools"] },
  { id:"bed-004", name:"Govt College of Education Bhopal",location:"Bhopal",state:"Madhya Pradesh",type:"Government",nirf:null,fees_annual:7500,    fees_total:15000,    entrance:"MP B.Ed CET",duration:"2 Years",package:"₹2–4 LPA",   naac:"B+",  highlight:"💰 Most affordable B.Ed in Bhopal. Under ₹10K/year",     course:"B.Ed", isGovernment:true, isMP:true,  specialties:["Education"],                      scholarship:"MP Govt scholarships. Gaon Ki Beti.",placed:["MP Govt Schools, Private schools"] },
  { id:"bed-005", name:"Lady Irwin College Delhi", location:"New Delhi",  state:"Delhi",           type:"Government", nirf:null,fees_annual:15000,   fees_total:30000,    entrance:"DU CET",   duration:"2 Years", package:"₹3–7 LPA",   naac:"A+",  highlight:"👩 Women's DU college. Good B.Ed program in Delhi",       course:"B.Ed", isGovernment:true, isMP:false, specialties:["Education"],                      scholarship:"DU + merit scholarships.",           placed:["Delhi schools, KV, Private schools"] },
  { id:"bed-006", name:"Amity Institute of Education",location:"Noida",   state:"Uttar Pradesh",  type:"Private",    nirf:null,fees_annual:102500,  fees_total:205000,   entrance:"Direct",   duration:"2 Years", package:"₹3–5 LPA",   naac:"A",   highlight:"🏙️ Amity brand B.Ed. Delhi-NCR school connects",         course:"B.Ed", isGovernment:false,isMP:false, specialties:["Education"],                      scholarship:"Merit scholarships.",                placed:["Private schools Delhi-NCR, International schools"] },
  { id:"bed-007", name:"LPU Phagwara (B.Ed)",    location:"Phagwara",   state:"Punjab",          type:"Private",    nirf:null,fees_annual:80000,   fees_total:160000,   entrance:"LPUNEST",  duration:"2 Years", package:"₹2.5–5 LPA", naac:"A+",  highlight:"💡 LPU brand. Affordable B.Ed. Good school placement",    course:"B.Ed", isGovernment:false,isMP:false, specialties:["Education"],                      scholarship:"LPUNEST merit scholarships up to 100%.",placed:["Private schools, CBSE schools, International schools"] },
  { id:"bed-008", name:"Jamia Millia Islamia Delhi",location:"New Delhi", state:"Delhi",           type:"Government", nirf:9,   fees_annual:15000,   fees_total:30000,    entrance:"JMI Entrance",duration:"2 Years",package:"₹3–7 LPA",   naac:"A++", highlight:"⭐ Central University NIRF Rank 9. Excellent B.Ed faculty",course:"B.Ed", isGovernment:true, isMP:false, specialties:["Education","Teacher Training"],   scholarship:"JMI minority + merit scholarships.", placed:["Delhi Govt schools, KV, NVS, Private schools"] }
];

OTHER_COLLEGES_RAW.forEach(c => {
    COLLEGES_DATA.push({
        ...c,
        isGovernment: c.isGovernment || false,
        isMP: c.isMP || false,
        extra: {
            branches: c.specialties || ["General"],
            scholarships: c.scholarship ? [c.scholarship] : ["Merit", "Need-based"],
            companies: c.placed || ["Various recruiters"],
            website: c.website ? (c.website.startsWith('http') ? c.website : "https://" + c.website) : "#",
            breakdown: { tuition: c.fees_annual, hostel: 0, other: 0 }
        }
    });
});

if (typeof module !== 'undefined') module.exports = { COLLEGES_DATA };

