-- USERS TABLE
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  mobile VARCHAR(10),
  password_hash VARCHAR(255),
  google_id VARCHAR(100),
  auth_provider VARCHAR(20) DEFAULT 'LOCAL',
  current_class VARCHAR(20) NOT NULL,
  stream VARCHAR(20),
  district VARCHAR(100),
  state VARCHAR(100),
  role VARCHAR(20) DEFAULT 'STUDENT',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- QUIZ RESULTS TABLE
CREATE TABLE quiz_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  science_score INT NOT NULL,
  commerce_score INT NOT NULL,
  arts_score INT NOT NULL,
  recommended_stream VARCHAR(20) NOT NULL,
  match_percentage INT NOT NULL,
  answers_json TEXT,
  taken_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_quiz_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- DEGREES TABLE
CREATE TABLE degrees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(200) NOT NULL,
  stream VARCHAR(20) NOT NULL,
  duration VARCHAR(50) NOT NULL,
  duration_years DECIMAL(3,1) NOT NULL,
  description TEXT,
  eligibility TEXT,
  entrance_exams VARCHAR(200),
  min_salary INT,
  max_salary INT,
  category VARCHAR(100),
  is_niche BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DEGREE SUBJECTS TABLE
CREATE TABLE degree_subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  degree_id BIGINT NOT NULL,
  semester INT NOT NULL,
  year_number INT NOT NULL,
  subject_name VARCHAR(200) NOT NULL,
  subject_type VARCHAR(20) DEFAULT 'CORE',
  CONSTRAINT fk_subject_degree FOREIGN KEY (degree_id) REFERENCES degrees(id) ON DELETE CASCADE
);

-- CAREERS TABLE
CREATE TABLE careers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  degree_id BIGINT NOT NULL,
  job_title VARCHAR(200) NOT NULL,
  industry VARCHAR(100),
  description VARCHAR(300),
  avg_min_salary INT,
  avg_max_salary INT,
  growth_level VARCHAR(20) DEFAULT 'MEDIUM',
  sector VARCHAR(20) DEFAULT 'BOTH',
  CONSTRAINT fk_career_degree FOREIGN KEY (degree_id) REFERENCES degrees(id) ON DELETE CASCADE
);

-- COLLEGES TABLE
CREATE TABLE colleges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  college_code VARCHAR(50),
  name VARCHAR(300) NOT NULL,
  short_name VARCHAR(100),
  state VARCHAR(100) NOT NULL,
  district VARCHAR(100) NOT NULL,
  city VARCHAR(100),
  address TEXT,
  phone VARCHAR(15),
  email VARCHAR(100),
  website VARCHAR(200),
  established_year INT,
  type VARCHAR(20) DEFAULT 'GOVERNMENT',
  gender VARCHAR(20) DEFAULT 'COED',
  nirf_ranking INT,
  naac_grade VARCHAR(5),
  hostel_available BOOLEAN DEFAULT FALSE,
  hostel_capacity INT,
  placement_rating DECIMAL(2,1),
  sports_ground BOOLEAN DEFAULT FALSE,
  library BOOLEAN DEFAULT TRUE,
  computer_lab BOOLEAN DEFAULT TRUE,
  science_lab BOOLEAN DEFAULT FALSE,
  streams_offered VARCHAR(100),
  annual_fees_min INT,
  annual_fees_max INT,
  total_seats INT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- COLLEGE COURSES TABLE
CREATE TABLE college_courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  college_id BIGINT NOT NULL,
  degree_id BIGINT NOT NULL,
  seats INT,
  annual_fees INT,
  admission_type VARCHAR(20) DEFAULT 'MERIT',
  CONSTRAINT fk_course_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE,
  CONSTRAINT fk_course_degree FOREIGN KEY (degree_id) REFERENCES degrees(id) ON DELETE CASCADE
);

-- ENTRANCE EXAMS TABLE
CREATE TABLE entrance_exams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  short_name VARCHAR(50) NOT NULL,
  description TEXT,
  conducting_body VARCHAR(200),
  exam_level VARCHAR(20) NOT NULL,
  streams_applicable VARCHAR(100),
  eligibility_class VARCHAR(20),
  min_percentage INT,
  exam_mode VARCHAR(20) DEFAULT 'ONLINE',
  application_start_date DATE,
  application_end_date DATE,
  exam_date DATE,
  result_date DATE,
  official_website VARCHAR(200),
  application_link VARCHAR(200),
  exam_fee INT,
  is_active BOOLEAN DEFAULT TRUE,
  academic_year VARCHAR(10),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- SCHOLARSHIPS TABLE
CREATE TABLE scholarships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(300) NOT NULL,
  description TEXT,
  provided_by VARCHAR(200),
  scholarship_type VARCHAR(20) NOT NULL,
  eligible_streams VARCHAR(100),
  eligible_classes VARCHAR(50),
  eligible_categories VARCHAR(100),
  eligible_gender VARCHAR(20) DEFAULT 'ALL',
  min_percentage INT,
  family_income_limit INT,
  amount_per_year INT,
  application_start_date DATE,
  application_end_date DATE,
  official_link VARCHAR(300),
  state VARCHAR(100),
  is_central BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE
);

-- SAVED DEGREES TABLE
CREATE TABLE saved_degrees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  degree_id BIGINT NOT NULL,
  saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_save_degree UNIQUE (user_id, degree_id),
  CONSTRAINT fk_saved_degree_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_saved_degree_degree FOREIGN KEY (degree_id) REFERENCES degrees(id) ON DELETE CASCADE
);

-- SAVED COLLEGES TABLE
CREATE TABLE saved_colleges (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  college_id BIGINT NOT NULL,
  saved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT unique_save_college UNIQUE (user_id, college_id),
  CONSTRAINT fk_saved_college_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_saved_college_college FOREIGN KEY (college_id) REFERENCES colleges(id) ON DELETE CASCADE
);

-- FEEDBACK TABLE
CREATE TABLE feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT,
  name VARCHAR(100),
  email VARCHAR(100),
  user_type VARCHAR(20),
  source VARCHAR(100),
  quiz_rating INT,
  improvement_text TEXT,
  other_feedback TEXT,
  submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_feedback_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- ADMIN AUDIT LOG TABLE
CREATE TABLE admin_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL,
  action VARCHAR(100),
  entity_type VARCHAR(50),
  entity_id BIGINT,
  old_value TEXT,
  new_value TEXT,
  performed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_admin FOREIGN KEY (admin_id) REFERENCES users(id)
);
