INSERT INTO scholarships (name, description, provided_by, scholarship_type, eligible_streams, eligible_classes, eligible_gender, amount_per_year, official_link, is_central) VALUES
('PM Scholarship for CAPF', 'Scholarship for children of martyrs of armed forces.', 'Central Government', 'MERIT', 'ALL', 'CLASS_12', 'ALL', 30000, 'https://desw.gov.in', 1),
('National Scholarship Portal (Post-Matric)', 'NSP scheme for SC/ST/OBC students.', 'Central Government', 'POST_MATRIC', 'ALL', 'CLASS_12, GRADUATE', 'ALL', 12000, 'https://scholarships.gov.in', 1),
('National Means cum Merit Scholarship', 'For students belonging to economically weaker sections.', 'Central Government', 'MERIT', 'ALL', 'CLASS_8', 'ALL', 12000, 'https://scholarships.gov.in', 1),
('Begum Hazrat Mahal National Scholarship', 'For minority community girl students.', 'Central Government', 'GIRL_CHILD', 'ALL', 'CLASS_9-12', 'GIRLS', 5000, 'https://maulana-education.in', 1),
('INSPIRE Scholarship (DST)', 'For students in the top 1% of their class in Science.', 'DST', 'MERIT', 'SCIENCE', 'CLASS_12', 'ALL', 80000, 'https://dst.gov.in', 1),
('MP Post-Matric SC Scholarship', 'State scholarship for SC students in MP.', 'MP Government', 'SC_ST_OBC', 'ALL', 'GRADUATE', 'ALL', 15000, 'https://scholarshipportal.mp.nic.in', 0),
('MP Post-Matric ST Scholarship', 'State scholarship for ST students in MP.', 'MP Government', 'SC_ST_OBC', 'ALL', 'GRADUATE', 'ALL', 15000, 'https://scholarshipportal.mp.nic.in', 0),
('MP Post-Matric OBC Scholarship', 'State scholarship for OBC students in MP.', 'MP Government', 'SC_ST_OBC', 'ALL', 'GRADUATE', 'ALL', 8000, 'https://scholarshipportal.mp.nic.in', 0),
('MP Medhavi Chhatra Yojana', 'For students with 85%+ in MP Board or 70%+ in CBSE.', 'MP Government', 'MERIT', 'ALL', 'CLASS_12', 'ALL', 25000, 'https://scholarshipportal.mp.nic.in', 0),
('MP Gaon Ki Beti Yojana', 'For girl students from rural areas.', 'MP Government', 'GIRL_CHILD', 'ALL', 'CLASS_12', 'GIRLS', 5000, 'https://scholarshipportal.mp.nic.in', 0),
('MP Pratibha Kiran Scholarship', 'For urban BPL girl students.', 'MP Government', 'GIRL_CHILD', 'ALL', 'CLASS_12', 'GIRLS', 5000, 'https://mp.gov.in', 0),
('MP Vikramaditya Free Education', 'Free education for EWS category students.', 'MP Government', 'GENERAL', 'ALL', 'GRADUATE', 'ALL', 10000, 'https://scholarshipportal.mp.nic.in', 0),
('AICTE PG Scholarship', 'For GATE qualified students pursuing M.Tech.', 'AICTE', 'MERIT', 'SCIENCE', 'GRADUATE', 'ALL', 148800, 'https://aicte-india.org', 1),
('ICCR Scholarship', 'For international exposure in arts and humanities.', 'ICCR', 'MERIT', 'ARTS', 'GRADUATE', 'ALL', 100000, 'https://iccr.gov.in', 1),
('UGC Scholarship for Differently Abled', 'Financial support for students with disabilities.', 'UGC', 'GENERAL', 'ALL', 'ALL', 'ALL', 15000, 'https://ugc.ac.in', 1),
('Tata Trust Scholarship', 'Merit and need-based support.', 'Tata Trusts', 'MERIT', 'ALL', 'ALL', 'ALL', 60000, 'https://tatatrusts.org', 0),
('Reliance Foundation Scholarship', 'Support for undergraduate students.', 'Reliance Foundation', 'MERIT', 'ALL', 'GRADUATE', 'ALL', 200000, 'https://reliancefoundation.org', 0),
('Sitaram Jindal Scholarship', 'Need-based scholarships for students.', 'Sitaram Jindal Foundation', 'GENERAL', 'ALL', 'ALL', 'ALL', 24000, 'https://sitaramjindalfoundation.org', 0),
('L\'Oreal India For Young Women in Science', 'Dedicated to girls pursuing science.', 'L\'Oreal India', 'GIRL_CHILD', 'SCIENCE', 'CLASS_12', 'GIRLS', 250000, 'https://loreal.com', 0),
('Aga Khan Foundation Scholarship', 'For postgraduate studies abroad.', 'Aga Khan Foundation', 'MERIT', 'ALL', 'GRADUATE', 'ALL', 500000, 'https://akdn.org', 0);
